### ISSUE TITLE
Create scale tests for Marathon

### ISSUE THREAD

**Issue by aquamatthias** [mesosphere/marathon#1789]
- [x] Come up with a plan for scale tests
- [x] How can we measure the results?
- [ ] How can we make reproduceable tests to compare different runs of the test?
- [ ] What is the limiting factor?
- [ ] How can we visualize the results?
