### ISSUE TITLE
Improve flexibility of tests

### ISSUE THREAD

**Issue by philipnrmn** [mesosphere/marathon#2099]
Our tests are currently very brittle. For example, [this change](https://github.com/mesosphere/marathon-ui/commit/35ceae196d4256a64f8c732f8ba91b635d45a490) caused [all these tests](https://travis-ci.org/mesosphere/marathon-ui/builds/77150114) to fail. 

We use React's [shallow rendering](https://facebook.github.io/react/docs/test-utils.html#shallow-rendering) feature in preference to the regular `renderIntoDom`. We therefore have no good way of referencing child elements. This leads to code like the following:
```
it("has correct number of total steps", function () {
  var totalSteps = this.component.props.children[3].props.children[2];
  expect(totalSteps).to.equal(2);
});
```

We could introduce a DOM implementation like [jsdom](https://github.com/tmpvar/jsdom) or [cheerio](https://github.com/cheeriojs/cheerio), or look at writing better test utilities to avoid this problem. 

One of our overall aims has been to make the test suite very fast. We should aim to maintain a respectable speed whilst making them more flexible, more legible, and easier to write. 

**[added by pierlo-upitup]**
Let's also start documenting our testing strategy for contributors.

**AC for this issue:**

- [ ] Decide on the best possible solution for writing meaningful and fast DOM-enabled tests (Enzyme, JsDOM, etc)
- [ ] Write or refactor a few tests trying to cover some DOM-based testing scenarios to serve as guideline
- [ ] Write documentation about our testing approach

Related discussion https://github.com/mesosphere/marathon-ui/pull/54

**Comment by aldipower** [comment]
For reference:
https://github.com/mesosphere/marathon/issues/1796

**Comment by aldipower** [comment]
I agree that this isn't very maintainable:
```
var totalSteps = this.component.props.children[3].props.children[2];
  expect(totalSteps).to.equal(2);
```
We should have a better solution to access the values.

**Comment by philipnrmn** [comment]
More evidence: removing an un-named `span` caused the tests to fail, suggested fix was to re-introduce a `span` to make the tests pass again: https://github.com/mesosphere/marathon-ui/pull/187

**Comment by pierlo-upitup** [comment]
Even more evidence: having to render HTML to a string and using regexes to determine contents: https://github.com/mesosphere/marathon-ui/pull/451#discussion-diff-46124472

**Comment by philipnrmn** [comment]
`cheerio` has been in the dependencies for a long time, we could reasonably just start using it in tests.

**Comment by pierlo-upitup** [comment]
Also worth noting:  what reported by @aldipower in #1796 
> The problem with jsDom is that it needs some specific versions of io.js for the current versions. On the other side an older version of jsDom isn't working out with the new versions of Mocha and React. So it's unusable for our setup in the moment.

is not true anymore. This has changed since the latest version of jsDOM only requires Node >= 4 which encapsulates the io.js stuff. After merging https://github.com/mesosphere/marathon-ui/pull/435 we should re-evaluate both options (cheerio and jsdom). It seems to me that mocha + jsdom is gaining a lot of traction in the React community so I'd like to take it for a whirl!

**Comment by aldipower** [comment]
Yes, finally we could use it! :+1:

**Comment by pierlo-upitup** [comment]
Adding https://github.com/airbnb/enzyme to the list of things we should consider!

**Comment by wendigo** [comment]
+1 for enzyme :)

**Comment by orlandohohmeier** [comment]
We might also consider introducing some kind of a dependency injection manager, to make it easier to replace things with mocks and stubs for better isolation.
