### ISSUE TITLE
Actor-based implementation of the TaskTracker

### ISSUE THREAD

**Issue by kolloch** [mesosphere/marathon#2916]
Originally part of #462.

Acceptance Criteria 
- [ ] task state is held in an actor
- [ ] the actor uses the WhenLeader infrastructure
- [ ] reads should be served from memory, writes propagated to Zookeeper and only confirmed when Zookeeper confirmed the write 
- [ ] acceptable performance
