### ISSUE TITLE
Resident Tasks: Extend MarathonTask state

### ISSUE THREAD

**Issue by meichstedt** [mesosphere/marathon#3041]
* Add information on pending reservations volumes.
* Decompose the `MarathonTask` protocol buffers object into a better scala-style abstraction.

Checklist to verify that this is finished:

Not done as part of this issue, now part of #3311:

  - [ ] check remaining `MarathonTask` occurrences (persistence related only)
  - [ ] `TaskFailures` (`Task.Id` instead of Mesos `TaskID`)
  - [ ] Check for other usages of Mesos `TaskID`, should only be used for communication with Mesos
  - [ ] `TaskSerializer` is package private
  - [ ] `MarathonTestHelper.*taskProto` methods are gone  

Done:

  - [x] check remaining `Task.Id` conversions (only towards the communication boundaries, e.g. towards Mesos)
  - [x] check remaining `Task.Id.idString` calls (only towards the communication boundaries, e.g. towards Mesos)
  - [x] `MarathonTasks` gone (all methods moved into `Task` and its sub structures)
  - [x] `TaskIDUtil` gone
  - [x] `Task.marathonTask` gone

**Comment by kolloch** [comment]
Done. Left-overs tracked in other issues.
