### ISSUE TITLE
Resident Tasks: Provide documentation

### ISSUE THREAD

**Issue by meichstedt** [mesosphere/marathon#3045]
subtasks
- [x] general usage
- [x] issues regarding data replication/loss
- [x] issues when using non-unique roles
- [x] resize inability for persistent volumes

**Comment by meichstedt** [comment]
Resolved via [#afbcd654](https://github.com/mesosphere/marathon/commit/afbcd654e069e1a4e78127632e1825ab994d5638)
