### ISSUE TITLE
Resident tasks: Various cleanup tasks

### ISSUE THREAD

**Issue by kolloch** [mesosphere/marathon#3474]
For documentation, Done:

- [x] TaskOpFactoryHelper should not create an Offer.Operation.Create when there are no volumes (we disallow that currently, but it's incorrect) --> validate there is a local volume if residency is defined

- [x] Mesos can get pretty confused when a framework re-uses a TaskId – we must at least append an attempt count to the TaskId if we don't generate a completely new one --> defer

- [x] Counting apps
  usages of _.launched.isDefined -> taskTracker.appsRunningTasksSync(app.id)

- [x] Extract an AppDefinitionSerializer and make "Residency serialization" part of its test --> defer

- [x] AppTaskLauncherActor has several places where it branches for (app.isResident)
  think about extracting this functionality and make it solid --> defer

- [x] OfferMatcherManagerActor: handling maxTasksPerOffer is incorrectly named because we may create several TaskOps per task but do not launch a task. We should think about how to throttle task ops/task launches. --> defer

- [x] DefaultTaskOpLogic
  the interfaces to launch/reserveAndCreateVolumes are not very nice --> defer

- [x] ResourceUtil.consumeResourcesFromOffer does not consume offered volumes and (labeled) reservations

- [x] TaskBuilder.buildIfMatches should be removed and build() used instead --> defer
