### ISSUE TITLE
Implement RunnableSpec as a super type for apps and pods

### ISSUE THREAD

**Issue by aquamatthias** [mesosphere/marathon#4293]
Steps to do:

- [ ] Define the RunnableSpec
- [ ] Replace occurrences of AppDefinition with RunnableSpec
- [ ] Create abstractions for specific use cases where AppDefinition is too specific
