### ISSUE TITLE
Make the LaunchQueue generic to handle Instances

### ISSUE THREAD

**Issue by aquamatthias** [mesosphere/marathon#4294]
- [x] All count logic must be based on Instances not tasks
- [ ] OfferMatching must be adapted to use aggregated resources
- [x] TaskLauncherActor must be based on instances not tasks
- [x] QueuedTaskInfo -> QueuedInstanceInfo
- [x] propagate InstanceChanges instead of TaskChanged to the LaunchQueue and other TaskUpdateStep consumers
