### ISSUE TITLE
Store / load Pods with all related data

### ISSUE THREAD

**Issue by aquamatthias** [mesosphere/marathon#4296]
- [ ] Create the relevant repositories
- [ ] Create all marshaller/unmarshaller
- [ ] Wire all repositories
