### ISSUE TITLE
Handle ExecutorId for Tasks and Instances

### ISSUE THREAD

**Issue by aquamatthias** [mesosphere/marathon#4299]
- [ ] Add ExecutorId to MarathonTask in marathon.proto
- [ ] Generate and set ExecutorId when launching Tasks/TaskGroups in TaskBuilder
- [ ] Migration: set executorId for existing tasks
- [ ] Compute Instance based on executorId

**Comment by aquamatthias** [comment]
Open Question: how does the TaskTracker now the number of tasks per instance? (without knowing the spec)

**Comment by unterstein** [comment]
Maybe this is obsolete in favor of storing Instances in ZK and adding executorId to this proto/case class? Or: Should we change the description to Instance instead?

/cc @jdef @meichstedt

**Comment by jdef** [comment]
probably change the description

**Comment by unterstein** [comment]
Should be completely obsolete now by storing instanced in ZK, #4398 and #4399
