### ISSUE TITLE
Add Authentication / Authorization for pods

### ISSUE THREAD

**Issue by aquamatthias** [mesosphere/marathon#4305]
- [x] add authentication to the pods endpoint
- [x] add authorization to the pods endpoint
- [ ] adapt group selector to be also filter pods
