### ISSUE TITLE
Deprecate non-SSE event callback mechanism

### ISSUE THREAD

**Issue by jasongilanfarr** [mesosphere/marathon#4675]

**Comment by janisz** [comment]
I'll add some story to this.

Callback system is good for small clusters and unfortunately it doesn't scale. Events are big and with many tasks/groups can reach tens of megabytes. This consume CPU time to parse events to JSON. Another downside of callbacks is missing on site filtering so all events are published. Using SSE is more efficient.

### TODO:
- [ ] #3257 update the docs by marking ` --event_subscriber http_callback` deprecated and whole callback section (cc @sascala )
- [ ] add warning when ` --event_subscriber http_callback` is used
- [ ] set end-of-support and end-of-life for http callback
- [ ] delete the code

**Comment by jasongilanfarr** [comment]
:+1:

**Comment by jasongilanfarr** [comment]
1.4:
[ ] docs and deprecation warnings
1.5:
[ ] EOL

**Comment by aquamatthias** [comment]
See https://phabricator.mesosphere.com/D389
