### ISSUE TITLE
Create Marathon 1.4.0-RC4

### ISSUE THREAD

**Issue by unterstein** [mesosphere/marathon#4836]
- [ ] 59c1e06 #4832 - typo fix per jdef's comment
- [ ] d5c9844 #4828 - Use async InstanceTracker methods in SchedulerActor
- [ ] a1297c6 #4798 - remove redundant use of '-Ywarn-unused-import' scalac option
- [ ] #4839 - command health checks for pods not supported until mesos 1.2
  - requires "known issue" for 1.4 release
- [ ] D333 - Do not block during reconciliation of health checks.
- [ ] D342 - Fixes #4842 by also writing deprecated pods to the proto.

**Comment by jasongilanfarr** [comment]
Can we get all of the "async Instance Trackers" in?

**Comment by jasongilanfarr** [comment]
Here is the full list of commits not in releases/1.4 since master @ 456af52b3aa39b31930e7d031d5ce1639694cdb7

I've added a `- [ ]` for commits I think should be cherry-picked into the appropriate branch, `X`s for _definitely not_, and `?` for maybe - we will need to update this list for any commits to master 456af52... this is based on the output of `git-cherry -v releases/1.4 master`

X + 57966ec82dba31d851fe3726b9ae8f82af9a0a80 Bump version for next dev cycle.
? - 07869fe36f9b7d3f4100ef753a63f96555f2c327 Mute ResidentTaskIntegrationTest.
? + 551458d1ed2a5c169b71981e0588cde66e33aab8 Fix test failures in MigrationTest.
? - 80840ca77105d316073f40b03372402aa9f7bcb1 Test app resources with embedded task failures.
- [ ] - 4c4be3413f0fbebeada9fb018d8c7c3365a3c4ed Log plan id instead of plan.
- [ ] - 46a86b3ea63231fa4da9bfc55664ca4d6be666c5 Fix issues with Entrypoint/Cmd in Docker images.
? - 2e5587fa504125ac097baa59b93d379bfb30ee2a Output debug logs for marathon integration tests.
- [ ] - 79381698885bd395cab2a605e40d1ed74e954ad8 clarify relationship between Condition and MesosTaskState
? + ef6a71d2b50de1f1e595e227b972b8fc87870602 Removed unused trait
- [ ] - 87c13a8710ca88c35ac1894b76f07b694a4b749d Fixes 4784 - Differ between AppNotFoundException and PodNotFoundException
? + e779930c95620d5c9b8943e6961255e2703db77d Remove unstable tag for MesosAppIntegrationTest
- [ ] - 7362a92c96920891877bd28acc269f323d01aac1 only set default network name for container networks
- [ ] - 320ee75e52b22b47a1b4abc56f77aefc02d77fc1 backport of pragma deprecated from network overhaul branch
- [ ] - 89740d036d2107116cb18dba56644fc35def077c Fixes 4790 - POD instances should not be killable via /v2/tasks
- [ ] - 4a19a8693c2ad6e166bc21ccbf7ea94583c60d6c MarathonSchedulerActor now respects launch queue tasks when scaling app
- [ ] - 1dfd99e355dc894e5dc4dde30bc6714e160381ec added version 1.3 information (#4768)
? - 918703727311f4c0a0d9836d282a1f0ded2302b8 Log rejected task ops on debug.
? - 56563ce2b5c00d805d6dee33db2b4db71378d81d Mute unstable tests - according to jenkins loop test.
- [ ] - ffd6bc625015055bfc8996ddee96fc23ba522661 Protect against garbage mesos versions
? - 6955e055b4fe7efb5a3676e2d791d0907d29fbcc Mark ResidentTaskInterationTest.persistent volume will be re-attached and keep state as unstable
? - bd6e6902059653edbf7a5acdab614ca966a93763 Rename unreachable strategy parameters to avoid API stutter.
- [ ] - 4c83608a27c6f9c5cba119ce67742156f4ac9c3d fixes #4808, relocate pod unreachbleStrategy to PodSchedulingPolicy type
- [ ] - 1a4d91cddd636d86f0b837482dd1c56a965ef012 Rework DeploymentManager logic
- [ ] - dcb7496df25f4ea70fa9ca02e0a12ffb1c21856f changelog for Marathon 1.4.0
? - 77a0759bfced8bed886a3ce7a20d1e251d6eef9e Move InstanceUpdateOpResolver to own file
- [ ] - efb38b944b33ea36f18966fdcc1b2f5495db9d76 Parse JSON event only once before broadcast (#4771)
- [ ]  6984205bf54241a1e4423c7631ccba260fc5e691 Turn off debug for jetty
? - 3889224e8a5949909e05cb3f04fd59a0a4357227 use patienceConfig for ZK timeouts
- [ ] - 12ca1235a69ff6eeb4a85c4f3a15c745d7a2f5c3 Increase default expunge timeout tasks
- [ ] - a8059112b3758e1c815779c16197230c38293641 add Unreachablestrategy to AppUpdate and apply
- [ ] - cc4cf6661cb17b17d1ffa44208edbde288524a55 Ss/pods docs (#4602)
- [ ] - 0cc19fc47de59614e0fcd1e7be95d2e8a1d325b7 pods typo
- [ ] - e354da0b258ff2cd21c53fab55d6d0c8b2e022b6 Change host port type  to ephemeral port number (#4820)
- [ ] - a0d2b9f53a8c61d1fd7185a76ce85afcd985dc72 Properly mark health check props as optional (#4812)
- [ ] - 4dfbbc1d0aea75347f8e2e26e9ce4368e82b81b2 Fix incorrect conversion from TaskStatus.timestamp to Timestamp
- [ ] - 114ea54d4774a059992ee00e1df93c2713ee4515 Removed unreachableInstances from QueuedInstanceInfo and QueuedInstanceInfoWithStatistics
- [ ] - ad881100cb0b38b0dd7d7cead8a413a06507a851 Remove additional condition from InstanceChangedEventsGenerator.events
? + 53f8f65f160f2757980327bdcbee50695bc1df23 Use one scheduled timer to send TaskStatusUpdates, not one timer for every update.
- [ ] - 8d821960fbed718208393b06a1a13a2dea9118e0 Handle OfferMatching timeouts as well as some performance improvements
- [ ] + bf74d2740cbe797c1ac754f2f76c8a208e8641a9 Moved InstanceUpdateOpResolver to correct package
- [ ] - 167f75c0304782a7bdd891cb36ea00397b3754ab Fixes #4824 - Use GroupRepository instead of AppRepository and PodRepository in MarathonSchedulerActor
- [ ] - f9e5213db5bf39bbf533f4374ff1800fd3905079 Abort on loss of leadership.
- [ ] - c8b1742efb8b5f3d65894de153dd4ade4fe774a2 Reverted the `group` function to not use `transitiveGroupsById`.
? - a4b539fdf4f3d8b0ff2b86e627dfbf791608496d Used `map` instead of `mapValues` in `RootGroup`.
- [ ] + 7b9ccda31510e0f3b9e420ebbb6c9e4eee5087ae typo fix per jdef's comment (#4832)
- [ ] + 18c469e97d3481b4ababcd7c19a311f4c116cea3 tiny pods edits
? - 8c14957a19cbd91499494f3b381bed3453f02bab Extract Instance.update into InstanceUpdater
? - 9612e113d46a12751ca8b363c76fcfe598785856 Renamed and moved InstanceUpdaterTest to correct name and package
- [ ] - d7bb4edd46412857acb5f2de1d9bb0bece633433 The LaunchQueueActor now forwards InstanceUpdate Events and sends Done in case of a non existing actor.
- [ ] - 85a32314d6c60d620c1fa2cc8d5660b23190cf47 Handle spaces in arguments correctly.
- [ ] + d5c984401ae0bad655c8d343ffd0298e2be4778e Use async InstanceTracker methods in SchedulerActor (#4828)
? + a1297c672abadbf487b11cf1cd37e76fd98bf3ed remove redundant use of '-Ywarn-unused-import' scalac option (#4798)
- [ ] + fedf081e3c53543765703c2635823ec979318ca3 add debug logging for status updates and offers
? + 8bf7ac157f11acb3a59f6d3ee9780b84b6172f74 Mark periodically failing tests Unstable
? + f03285b20817909a1c08169436b26af5520c0a1b Marked frequently failing integration tests as `Unstable`
? + 75e4753f03985f6eaf43a5a15d812f8ede2920e6 Re-enable docker test.
- [ ] + 91cdc7e91afa774ca7eb5a04232cf8591b02f570 add a docker container label with mesos task id (#4492)
? + 0309a4e561405d9bb0a554d4799ac58f20ae9d4c Add TestCase for handling InstanceUpdate events in the LaunchQueue
- [ ] + 39cc4b8df32f16c7430eb04c1895bd72dc58b9ff Do not block during reconciliation of health checks.
- [ ] + ce0ec900338051ae8220a5a5ed9f285288235600 Workaround added concerning the Docker issue with external volumes. (#4804)
? + 76c96c40f4991aa17fe6f7fbc088f0719e9ff85d Remove obsolete Unstable MarathonStoreTest
? + d385279c9164c08bb91a6bcb4fde2797e3424e37 remove Unstable
? + ccd64d70c642f025d754aaace798ff358077e246 sync scalariform formatting
- [ ] + 00a29d9f6706f88bf37e3f4474015d49f5ebb984 update changelog for 1.4.0-rc-2 and 1.4.0-rc-3
? + 4cb6639708d37bc4e6a51d4cf29604f0e3646581 removed `createHackInstance`
? + 3c8048536c99a311dab6d421ced8b9649f959bb6 fix dependencies
- [ ] + 6578976721c466d3f4285480f8415ad224cc87d1 Fixes #4842 by also writing deprecated pods to the proto.
? + 3f6c5fe226ffc53e7f7d2beeb7cea38c0725a915 Lower minimum coverage to have it pass.
- [ ] + 24598991a7d653a0e33cd13cd5935ffad9ceb2e4 Mark task_lost_expunge_gc command line parameter as deprecated.
- [ ] + bb90b74c66c838579cc0d5ba611810adb233d357 added mesos v1.2 compat note
- [ ] + 23030fe92c5e7b27432f740ab43d25bcad63310a initial support for pragma omitEmpty
- [ ] + 5d5d7688794ea4f649184d3d2184bb6f767cca5a line edits (#4630)
- [ ] + 00346f7e1b98afb06b4525a1c9904d389e16b925 fix bugs in example, in groups docs
? + 90387d575d276c3c70e1630c45bbc781c421a1d5 Fix MarathonTest helper to not use internal objects (persistence/persistent store)
? + d845cd3415e9799ad22ef63113aa5e3ad8240834 Deterministically generate raml models
X + 9dc73ae7bf1833f8c5353c8d160f43a87dcab4c2 Delete Legacy Storage (#4852)
? + 90a54708baaa7130ceb35ed80d5e120aa6b45a8b fixed contributing.md to make the stylechecker quotation works correctly
? + cf24e945f8731d204021e20b699051fd0d445809 Simplify InstanceTracker by removing unused method (#4795)
? + f146477332ddb19dd4e33949ed7fffb50e1f42f3 Create SerialIntegrationTest for running time-sensitive integration tests
- [ ] + 456af52b3aa39b31930e7d031d5ce1639694cdb7 Hide Pod and AppRepository - Group owns them (#4824).

**Comment by jeschkies** [comment]
pick https://phabricator.mesosphere.com/D307 https://github.com/mesosphere/marathon/commit/d11b27e7b83a1c0337c1f2b12eb072d3c97f76b0

**Comment by unterstein** [comment]
pick https://github.com/mesosphere/marathon/pull/4890

**Comment by jasongilanfarr** [comment]
pick 95125c4f6944c7ee398a39faa85cba96cee64cba (D353)

**Comment by aquamatthias** [comment]
Cherry picked those commits: 

- 7b9ccda31510e0f3b9e420ebbb6c9e4eee5087ae typo fix per jdef's comment (#4832)
- 18c469e97d3481b4ababcd7c19a311f4c116cea3 tiny pods edits
- d5c984401ae0bad655c8d343ffd0298e2be4778e Use async InstanceTracker methods in SchedulerActor (#4828)
- a1297c672abadbf487b11cf1cd37e76fd98bf3ed remove redundant use of '-Ywarn-unused-import' scalac option (#4798)
- fedf081e3c53543765703c2635823ec979318ca3 add debug logging for status updates and offers
- 8bf7ac157f11acb3a59f6d3ee9780b84b6172f74 Mark periodically failing tests Unstable
- f03285b20817909a1c08169436b26af5520c0a1b Marked frequently failing integration tests as `Unstable`
- 39cc4b8df32f16c7430eb04c1895bd72dc58b9ff Do not block during reconciliation of health checks.
- ce0ec900338051ae8220a5a5ed9f285288235600 Workaround added concerning the Docker issue with external volumes. (#4804)
- 76c96c40f4991aa17fe6f7fbc088f0719e9ff85d Remove obsolete Unstable MarathonStoreTest
- d385279c9164c08bb91a6bcb4fde2797e3424e37 remove Unstable
- 00a29d9f6706f88bf37e3f4474015d49f5ebb984 update changelog for 1.4.0-rc-2 and 1.4.0-rc-3
- 4cb6639708d37bc4e6a51d4cf29604f0e3646581 removed `createHackInstance`
- 3c8048536c99a311dab6d421ced8b9649f959bb6 fix dependencies
- 6578976721c466d3f4285480f8415ad224cc87d1 Fixes #4842 by also writing deprecated pods to the proto.
- 3f6c5fe226ffc53e7f7d2beeb7cea38c0725a915 Lower minimum coverage to have it pass.
- 24598991a7d653a0e33cd13cd5935ffad9ceb2e4 Mark task_lost_expunge_gc command line parameter as deprecated.
- bb90b74c66c838579cc0d5ba611810adb233d357 added mesos v1.2 compat note
- 23030fe92c5e7b27432f740ab43d25bcad63310a initial support for pragma omitEmpty
- 5d5d7688794ea4f649184d3d2184bb6f767cca5a line edits (#4630)
- 00346f7e1b98afb06b4525a1c9904d389e16b925 fix bugs in example, in groups docs
- d845cd3415e9799ad22ef63113aa5e3ad8240834 Deterministically generate raml models
- 90a54708baaa7130ceb35ed80d5e120aa6b45a8b fixed contributing.md to make the stylechecker quotation works correctly
- 456af52b3aa39b31930e7d031d5ce1639694cdb7 Hide Pod and AppRepository - Group owns them (#4824).
- b9e2c6d0965d4f73b019a7934b933e0868d8d2a2 store URL validation should not require network connectivity
- d11b27e7b83a1c0337c1f2b12eb072d3c97f76b0 Update kill selection in App as well.
- 2cab7c935f9916caa00b45a2ce8ac86bda749367 Graph call sequence for creating an app.
- 938a0392469708be01e9f1019c72f9e31fd90f87 fix various bugs in our RAML specification. add omitEmpty to some fields for cleaner output.
- c3b6939f9f4a0821c012e611d9da6a97f8e104c4 remove useless logs from test output
- 292d770c10a080b57f50810ae047ebb71fb27a5a Log when instance becomes UnreachableInactive.
- 3a5c5b85d11c77f17cda62e51cbc4dca9bb3229a Quote some vars and make sed more explicit (#4890)
- 6c0149d0d1592bb0bc5509a1b5e4770605f87905 Disallow usage of Command Checks on Pods until mesos supports them (#4872)
- c8924aa8d3a21346a7728c881d6378dc969e320c Inform the rate limiter for pods and apps (#4863)
- 562c5520033de96384a707c1efa0b5c2ebfcbaef Fixes #4882 by renaming KillSelection YoungestFirst->YOUNGEST_FIRST and OldestFirst->OLDEST_FIRST.



Did not cherry pick those commits:

- 2e5587fa504125ac097baa59b93d379bfb30ee2a Output debug logs for marathon integration tests.
- ef6a71d2b50de1f1e595e227b972b8fc87870602 Removed unused trait
- e779930c95620d5c9b8943e6961255e2703db77d Remove unstable tag for MesosAppIntegrationTest
- 53f8f65f160f2757980327bdcbee50695bc1df23 Use one scheduled timer to send TaskStatusUpdates, not one timer for every update.
- 75e4753f03985f6eaf43a5a15d812f8ede2920e6 Re-enable docker test.
- 91cdc7e91afa774ca7eb5a04232cf8591b02f570 add a docker container label with mesos task id (#4492)
- 0309a4e561405d9bb0a554d4799ac58f20ae9d4c Add TestCase for handling InstanceUpdate events in the LaunchQueue
- ccd64d70c642f025d754aaace798ff358077e246 sync scalariform formatting
- 90387d575d276c3c70e1630c45bbc781c421a1d5 Fix MarathonTest helper to not use internal objects (persistence/persistent store)
- 9dc73ae7bf1833f8c5353c8d160f43a87dcab4c2 Delete Legacy Storage (#4852)
- cf24e945f8731d204021e20b699051fd0d445809 Simplify InstanceTracker by removing unused method (#4795)
- f146477332ddb19dd4e33949ed7fffb50e1f42f3 Create SerialIntegrationTest for running time-sensitive integration tests
- d3376ad38848bd020bd254f121da8b66e64efda7 Use curator-test to manage a zookeeper instance
- 3f862d6ed095d2f57d790944324d31adba894c15 test cleanup.  fixed flaky tests.  pep8
- cc82191e0fffff21b1d6b1c3380089513473affb Mark Unstable integration tests as SerialIntegrationTest
- 20b8ba6f2de022e55d5189d1c2937cb1c05c94a4 universe test cleanup
- 615614c2f72e7647e3174f4f965e35ab5559f90f cleaning up pod si tests
- 91980ff73465d6cbcedffc1eec33778b37f38d3a advance tests for framework deployments on marathon
- 9e84f584daedc79722ef7a9eb66d3eae3b33d9ed use latest released marathon ui version, see https://github.com/mesosphere/marathon/pull/4857
- a34f38694bd5c7a0bbe55280afeecb76d48de09a make ZookeeperServer start() capable of restarting. docs
- b476f32a9dae14674bd758ff650c7fd2fe6f778e Remove support for the legacy election style (twitter)
- f654a82ebadfb7764532c5357d97d25d0c35aeed Fixes #4764 - Make legacy code accessing the first task of an instance less painful
