### ISSUE TITLE
Create Marathon 1.4.0-RC7

### ISSUE THREAD

**Issue by zen-dog** [mesosphere/marathon#4969]
- [x] 69d4b26fd6c7c480c76e22f4e73027939bccbcdc (already picked) Fixes #4991 by specifically testing, if a property in the docker section is set, but is not supported.
- [x] 3716181f59e11fba61bd16fc864c98a9181cbf7f (already picked) Use api-console in github pages
- [x] 91cdc7e91afa774ca7eb5a04232cf8591b02f570 (already picked) add a docker container label with mesos task id (#4492)
- [x] 205589b84c3038e9e07145626d9dee9f5abc50ff (already picked) Documentation: pods typo fix
- [x] 96fd203e38aeeaa7743ef7541e13749a6c4c5731 (already picked) Documentation: first draft of task handling (#4642)
- [x] 970ac26b4c8f4eac8336a648822ad1f51fed65d6 (already picked) Documentation: typo fix on task handling config page
- [x] 370691989011e8b96210a73e866e34bd591889b2 (already picked) Documentation: markdown typo
- [x] c4df9c662fb3300ba8bf8336e38935c051a53b60 (already picked) Documentation: markdown typo fixes
- [x] 1d4d52ff0fadfeb5f101d1c70bd1c59ac7063758 (already picked) Documentation: Typo (#4939) directoy to directory
- [x] bd1c69a23251c5361ae879a1a9544067a52f5664 (already picked) Make sure the HistoryActor only stores task failures once.
- [x] fe00f46ac7978ba2489c8e6a234073694574a0b5 (already picked) Documentation: peg doc updates to release branch (#4937)
- [x] 13add63d355ff4fe13798f31627c5c4c1890a293 (already picked) Documentation: apps + groups can be in a group (#4964)
- [x] cf3d544806b3dfd40caca6605667cef3a9db4f9d (already picked) Remove authorization from /ping endpoint
- [x] 589ad6a40f38d010a9117b2450b6bae1b34805c5 (already picked) Documentation: Fixed DC/OS link to dcos.io. (#4979)
- [x] 6467d124aa636ce4b78dec4a6a831ae4eec59a00 (already picked) Log all Mesos capabilities on level Info instead of Debug.
- [x] 5b712987663a6815e0d53e68a1d0068523864d95 (already picked) Documentation: Call out the artifact store as deprecated.
- [x] ef13b44b0a3e5cc7a85e137f2efe585ecf5437ae (already picked) Make TaskResources async (#4807)
- [x] 14177b0119c91c8687296893a9755ad71ee79b3a (already picked) Fixes #4932 | GET on empty apps list result 500 exception (#4940)
- [x] c52b8dd077bda541543f92a0962c2aada442b5d6 (already picked) Use async instance tracker methods in TaskKiller (#4800)
- [x] 79fe121505749fe709456211e9b80222d7b677c3 (already picked) Close #4722 by moving event subscription of the InstanceKillProgressActor.
- [x] 195295e8873e67ca59ce5ec3dea0af21f8de08df (already picked) Upgrade low-risk libraries to the latest patch release (#4983).
- [x] a1d7b569e795b5f8bf84cc7b22a66031b3a366ec (already picked) Fixes #5016 by validating, if the app id is non empty.
- [x] bd3096efdfc95407f2a47d25ac65e649d9c3e740 (already picked) [D451](https://phabricator.mesosphere.com/D451) Fixes #4966 by using the resulting boolean value instead of mapping into the scallop option.
- [x] 6834f418470ca015522429d2629ebc7f125893fc (already picked) [D455](https://phabricator.mesosphere.com/D455) Fixes #5024 by using the correct validator for validating app dependencies.

**Comment by aquamatthias** [comment]
-[ x ] 69d4b26fd6c7c480c76e22f4e73027939bccbcdc (already picked) Fixes #4991 by specifically testing, if a property in the docker section is set, but is not supported.

**Comment by jeschkies** [comment]
Please add [D443](https://phabricator.mesosphere.com/D443) once it landed.

**Comment by jeschkies** [comment]
Cherry picked D443 with https://github.com/mesosphere/marathon/commit/79fe121505749fe709456211e9b80222d7b677c3

**Comment by jeschkies** [comment]
Cherry picked #4983 with https://github.com/mesosphere/marathon/commit/195295e8873e67ca59ce5ec3dea0af21f8de08df

**Comment by aquamatthias** [comment]
Please add https://phabricator.mesosphere.com/D451

**Comment by aquamatthias** [comment]
Please add https://phabricator.mesosphere.com/D447

**Comment by jeschkies** [comment]
Please add https://phabricator.mesosphere.com/D455

**Comment by jeschkies** [comment]
Release tirggered with https://github.com/mesosphere/marathon/commit/8ceec6c95faf667c4580c21ca65be0e257069f51

**Comment by jeschkies** [comment]
Release broke. Here is a quick fix https://phabricator.mesosphere.com/D456.

**Comment by jeschkies** [comment]
PR for Open DC/OS https://github.com/dcos/dcos/pull/1176
PR for DC/OS EE https://github.com/mesosphere/dcos-enterprise/pull/538
