### ISSUE TITLE
Feature Parity with TeamCity Release Jobs

### ISSUE THREAD

**Issue by marcomonaco** [mesosphere/marathon#5063]
[Subtasks](https://github.com/mesosphere/marathon/issues?utf8=✓&q=%235063%20in%3Atitle%20):

* [x] [Build Runnable jar in Jenkins #5173](https://github.com/mesosphere/marathon/issues/5173)
* [x] [Create deb and rpm Package #5172](https://github.com/mesosphere/marathon/issues/5172)
* [ ] [Upload Tagged Native Packages to Package Server #5069](https://github.com/mesosphere/marathon/issues/5069)
* [ ] [Upload Tar and Sha of Tagged Package to S3 #5194](https://github.com/mesosphere/marathon/issues/5194)
* [x] [Create tar with sbt for tagged packages #5068](https://github.com/mesosphere/marathon/issues/5068)
* [ ] [Upload Snapshot Packages to S3 #5066](https://github.com/mesosphere/marathon/issues/5066)
* [x] [Create tar with sbt for snapshot packages #5065 ](https://github.com/mesosphere/marathon/issues/5065)
* [ ] [Upload Release Docker Image to Docker Hub #5071](https://github.com/mesosphere/marathon/issues/5071)
* [ ] [Upload Snapshot Docker Image to Docker Hub #5195](https://github.com/mesosphere/marathon/issues/5195)

# Blockers

* [ ] [Archive Build Artifacts to S3 #5174](https://github.com/mesosphere/marathon/issues/5174)
* [ ] [Change Package Version Before Release #5196](https://github.com/mesosphere/marathon/issues/5196)
* [ ] [Tag Commit and Push to Repo #5197](https://github.com/mesosphere/marathon/issues/5197)

# Out of Scope
* [Migrate sbt assembly to sbt native packager (for rpm and deb artifacts) for tagged packages #5067](https://github.com/mesosphere/marathon/issues/5067)
* [Migrate sbt assembly to sbt native packager (for rpm and deb artifacts) for snapshot packages #5064](https://github.com/mesosphere/marathon/issues/5064)

**Comment by marcomonaco** [comment]
Task breakdown: 
- #5064

**Comment by marcomonaco** [comment]
#5064

**Comment by jeschkies** [comment]
I'd like to follow the proposed approach with the Docker build in https://github.com/mesosphere/marathon/issues/5071. Each commit creates the tar, deb and rom packages and the sha1. The packages are archived on the Jenkins master or better an S3 bucket annotated with the commit hash. A release would just mean to grab the packages for a certain commit and publishing them.

**Comment by jeschkies** [comment]
As discussed with @aquamatthias the artifacts should be archived on S3.

**Comment by jeschkies** [comment]
I've cut [VELOCITY-1253](https://jira.mesosphere.com/browse/VELOCITY-1253) to setup S3.

**Comment by jeschkies** [comment]
https://github.com/mesosphere/marathon/issues/5174is the tracking issue for S3 archiving.

**Comment by meichstedt** [comment]
Note: This issue has been migrated to https://jira.mesosphere.com/browse/MARATHON-1734. For more information see https://groups.google.com/forum/#!topic/marathon-framework/khtvf-ifnp8.
