### ISSUE TITLE
Release Marathon 1.4.0-RC8

### ISSUE THREAD

**Issue by timcharper** [mesosphere/marathon#5110]
Cherry picks:
- [x] Fixes #5076 by validating MaxPer constraint specifically
- [x] Improve performance of dependency graph computations [D476](https://phabricator.mesosphere.com/D476) -- cherry picked with https://github.com/mesosphere/marathon/commit/81afd3b1f87b7d2e8d5e8085842a9497ffd62de5
- [x] Performance improvements
  - [x] In 1.1 branch 334734390f0c22ea10e5b9746f5430168dcd43cb
  - [x] [D481](https://phabricator.mesosphere.com/D481) -- cherry picked with https://github.com/mesosphere/marathon/commit/5407f02d19cc32791087289d7ceff051b5408d6d
- [x] `NetworkSpec` plugin API [D490](https://phabricator.mesosphere.com/D490) -- cherry picked with https://github.com/mesosphere/marathon/commit/96e391b74ea88ba95796c1a7885bfd6c274ad642
- [x] Generate DiscoveryInfo for pod container endpoints (#5087) -- cherry picked with https://github.com/mesosphere/marathon/commit/593ca148d2a6063de8b769b34356e30c9e8d92d3
- [x] Clarify rexray documentation (#5117) -- cherry picked with https://github.com/mesosphere/marathon/commit/f997313e5c77f6f16390a53c25c7eb2bb4bde8c6
- [x] Define network-scope label for ipaddress.discovery.ports (#5144) -- cherry picked with https://github.com/mesosphere/marathon/commit/4578defc082c5c0d80adc115c1d6902bb4806d36
- [x] Increase queue length for storage operations, helps large migrations (#5083) -- cherry picked with https://github.com/mesosphere/marathon/commit/cbdadb2c0944537e2d090678a9dc6a44b0448365
- [x] [D496](https://phabricator.mesosphere.com/D496) pods allow duplicate endpoint ports -- cherry picked with https://github.com/mesosphere/marathon/commit/ea94593bc9a6edcae0083420a4dd65436d2b7244
- [x] PUT on /v2/apps has a PATCH semantic. https://github.com/mesosphere/marathon/pull/5157
- [x] doc link updates (#5084)

**Comment by alexispetalas** [comment]
Hi tim, what about this PR?? https://github.com/mesosphere/marathon/pull/4107

**Comment by aquamatthias** [comment]
- [ ] [D496](https://phabricator.mesosphere.com/D496) pods allow duplicate endpoint ports

**Comment by jdef** [comment]
#4107 is already in the releases/1.4 branch, thanks

**Comment by jdef** [comment]
unless something crazy comes up tomorrow .. we should try to land RC8 ASAP because others in the org are waiting on it

**Comment by jeschkies** [comment]
https://github.com/mesosphere/marathon/issues/5144 depends on https://github.com/mesosphere/marathon/commit/1c9f0cd2236707538623a52bf0aedea95ac2d2b1 which introduces `PortDiscovery` class.

**Comment by jeschkies** [comment]
@alexispetalas the PR should have landed on master with https://github.com/mesosphere/marathon/pull/4418.

**Comment by jeschkies** [comment]
Release is currently blocked by https://github.com/mesosphere/marathon/pull/5157.

**Comment by jdef** [comment]
dcos/dcos PR: https://github.com/dcos/dcos/pull/1231
