### ISSUE TITLE
Create mock managed service

### ISSUE THREAD

**Issue by marcomonaco** [mesosphere/marathon#5150]
- Design prototyping platform
- Will be used in our integration test

**Comment by jasongilanfarr** [comment]
Could I get some context on this please?

**Comment by timcharper** [comment]
Prior to creating the RAML spec for managed services, we plan to create a simple mock managed service that supports the API that we can use as a proof-of-concept implementation, and, as a stub service used in our integration tests.

**Comment by timcharper** [comment]
- [ ] Mock managed service uninstall
- [ ] Mock managed dry run
- [ ] Mock managed upgrade with deployment
- [ ] mock decision points

**Comment by marcomonaco** [comment]
Closing in favor of https://github.com/mesosphere/marathon-dcos-plugins/issues/127
