### ISSUE TITLE
Documentation and RAML spec for v0 managed services protocol

### ISSUE THREAD

**Issue by marcomonaco** [mesosphere/marathon#5151]
- Interaction diagrams
- Describe API endpoints:
  - Marathon <-> Scheduler
  - UI <-> Marathon
  - UI <-> Scheduler (proxied, more-or-less transparent endpoints; document in one place for consistency)

Acceptance:

- [ ] All schema objects are defined in RAML
- [ ] All endpoints are described with RAML
- [ ] Interactions are documented with diagrams

**Comment by marcomonaco** [comment]
Closed in favor of https://github.com/mesosphere/marathon-dcos-plugins/issues/126
