### ISSUE TITLE
Support framework authentication

### ISSUE THREAD

**Issue by ConnorDoyle** [mesosphere/marathon#638]
See the [Mesos Credential protobuf message definition](https://github.com/apache/mesos/blob/master/include/mesos/mesos.proto#L690)

**Sub-tasks:**
- [x] Accept a principal as a command-line argument.
- [x] Accept a path to a secret as a command-line argument.
- [x] Pass principal and secret to the `SchedulerDriver`
- [x] Set the principal value in the `FrameworkInfo` message during registration.

_Notes:_ Secret should not be necessarily required, for maximum flexibility in auth modes.
