### ISSUE TITLE
Integrate SSO and IDM for browser app and RESTful web services

### ISSUE THREAD

**Issue by preillyme** [mesosphere/marathon#883]
Integrated SSO and IDM for browser app and RESTful web services.
Built on top of the OAuth 2.0, Open ID Connect, JSON Web Token (JWT) and SAML 2.0 specifications.

- [ ] SSO and Single Log Out for browser applications
- [ ] Social Broker.  Enable Google, Facebook, Yahoo, Twitter social login with no code required.
- [ ] Optional LDAP/Active Directory integration
- [ ] Optional User Registration
- [ ] Password and TOTP support (via Google Authenticator).
- [ ] Client Cert Auth.
- [ ] User session management from both admin and user perspective
- [ ] Customizable theme(s) for user facing pages: login, grant pages, account management, emails and admin console make them all customizable!
- [ ] OAuth Bearer token auth for REST Services
- [ ] Integrated Browser App to REST Service token propagation
- [ ] Admin REST API
- [ ] OAuth 2.0 Grant requests
- [ ] CORS Support
- [ ] CORS Web Origin management and validation
- [ ] Completely centrally managed user and role mapping metadata.  (e.g., minimal configuration at the application side)
- [ ] Admin Console for managing users, roles, role mappings, applications, user sessions, allowed CORS web origins, and OAuth clients.
- [ ] Deployable as a WAR.
- [ ] Support Tomcat, Jetty and Pure Javascript applications.
- [ ] HTTP Security Proxy for environments/platforms/languages that don't have a proper client adapter
- [ ] Javascript/HTML 5 adapter for pure Javascript apps
- [ ] Session management from admin console
- [ ] Revocation policies
- [ ] Password policies
- [ ] OpenID Connect Support
- [ ] SAML 2.0

**Comment by aquamatthias** [comment]
That is more a collection of topics than an issue. Will cover these in separate tickets.
